# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 03:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Region', models.CharField(max_length=32)),
                ('Regional_Drought_Stage', models.CharField(max_length=32)),
                ('Reservoir_Name', models.CharField(max_length=32)),
                ('Reservoir_Storage', models.DecimalField(decimal_places=4, max_digits=10)),
                ('Reservoir_Level', models.DecimalField(decimal_places=4, max_digits=7)),
                ('Date', models.CharField(max_length=32)),
            ],
        ),
    ]
