# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 03:34
from __future__ import unicode_literals

from django.db import migrations
def initial_stations(apps, schema_editor):
    Station = apps.get_model('stations', 'Station')
    Station(Region=u'新竹', Regional_Drought_Stage=u'黃燈', Reservoir_Name=u'寶山+寶二', Reservoir_Storage='2500.00', Reservoir_Level='250.00',Date=u'20170804').save()


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
    ]
